#!/bin/bash


if $# -ne 1
then
	echo "wrong number of arguments" 
	exit 0
fi

dune exec bin/main.exe -- tmp-server client send-message -server ec2-52-45-110-109.compute-1.amazonaws.com:8181 -message "$1"


